# ADDING CUSTOM SSL CERTS
# https://github.com/bitnami/containers/tree/main/bitnami/nginx#using-custom-ssl-certificates


# https://github.com/bitnami/containers/tree/main/bitnami/wordpress-nginx

# https://hub.docker.com/r/bitnami/wordpress-nginx

# curl -sSL https://raw.githubusercontent.com/bitnami/containers/main/bitnami/wordpress-nginx/docker-compose.yml > docker-compose.yml

# curl -sSL https://raw.githubusercontent.com/chrissze/chrissze.github.io/main/docker/wp/compose.yaml > compose.yaml

version: '2'
services:
  mariadb:
    image: docker.io/bitnami/mariadb:11.3
    volumes:
      - 'mariadb_data:/bitnami/mariadb'
    environment:
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - ALLOW_EMPTY_PASSWORD=yes
      - MARIADB_USER=bn_wordpress
      - MARIADB_DATABASE=bitnami_wordpress
  wordpress:
    image: docker.io/bitnami/wordpress-nginx:6
    

    ports:
      - '80:8080'
      - '443:8443'
      
    volumes:
      - 'wordpress_data:/bitnami/wordpress'
      
    depends_on:
      - mariadb

    environment:
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - ALLOW_EMPTY_PASSWORD=yes
      - WORDPRESS_DATABASE_HOST=mariadb
      - WORDPRESS_DATABASE_PORT_NUMBER=3306
      - WORDPRESS_DATABASE_USER=bn_wordpress
      - WORDPRESS_DATABASE_NAME=bitnami_wordpress   
      
volumes:
  mariadb_data:
    driver: local
  wordpress_data:
    driver: local
