echo "hi I'm $USER  .bashrc 644, start"


# USER VARIABLES

export PS1='\d \u@\W $ '

# to make rust compiler woking, xcode 15 in MacOS 15 Sequoia
export LIBRARY_PATH=/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/lib

HISTSIZE=999

HISTFILESIZE=999




# USER FUNCTIONS

cd() { builtin cd "$@" && ls -laph && echo && pwd && echo; }


la() {
    if [ -z "$1" ]; then
        ls -ahlp
    else
        shopt -s dotglob nocaseglob; ls -adhlp [$1]* .[$1]*; shopt -u dotglob nocaseglob;
    fi
}

ree() { mkdir /tmp/ree && rsync -av -e 'ssh -p 55555' $1 /tmp/ree/ && rsync -av /tmp/ree/* -e 'ssh -p 55555' $2 && rm -rf /tmp/ree; }


# USER ALIAS

alias gpush="git add . && git commit -m 'pro' && git push"

alias gpull="git fetch --all && git reset --hard origin/master"

alias hi=history

alias nan='nano -cv'

alias o1='ssh -p 55555 almalinux@o1.220122.xyz'

alias o2='ssh -p 55555 almalinux@o2.220122.xyz'


alias pipup='pip3 install --upgrade pip'

alias pipr='pip3 install -r requirements.txt'

alias pmg='python3 manage.py makemigrations && python3 manage.py migrate'

alias prun='python3 manage.py runserver'

alias py='python3'

alias pycustom='cd ~/github/pizzapy/venv/lib/python3.11/site-packages && ln -s ~/github/batterypy batterypy && ln -s ~/github/dimsumpy dimsumpy'

alias pyv='python3 -m venv venv && source venv/bin/activate && pip3 install --upgrade pip && pip3 list && which python3 && python3 -V'



alias re="rsync -av -e 'ssh -p 55555'"

# I cannot use rs alias due to Mac SIP protected rs command
alias rus=rust-script  


alias rms='rename "s/ //g" *'

alias sha='shasum -a 256'

alias sou='source ~/.bash_profile'

alias venv='source venv/bin/activate'

alias vir="vim -R -c 'syntax on'"



echo "hi I'm $USER  .bashrc 644, end"
