[ -z "$PS1" ] && return

echo "$HOME/.bashrc    starts."

# USER ALIAS
    
    alias gpush="git add . && git commit -m 'cs' && git push"
    
    alias gpull="git stash && git fetch --all && git reset --hard origin master"
    
    alias hi=history
    
    alias pmg='python3 manage.py makemigrations && python3 manage.py migrate'
    
    alias prun='python3 manage.py runserver'
    
    alias pipup='pip3 install --upgrade pip'
    
    alias pipr='pip3 install -r requirements.txt'
    
    alias psq='psql -U postgres'
    
    alias pvenv='python3 -m venv venv && source venv/bin/activate && pip3 install --upgrade pip'
    
    alias py=python3

    alias re="rsync -avP -e 'ssh -p 55555'"

    alias rm='rm -i'
    
    alias sha=sha256sum
    
    alias sou='source ~/.bash_profile'
    
    alias sulo='sudo su --login'
    
    alias tip='cardano-cli query tip --mainnet'
    
    alias tnode='tmux attach -t node'
    
    alias tweb='tmux attach -t web'
    
    alias venv='source venv/bin/activate'
    
    


# USER FUNCTIONS
    
    cd() { builtin cd "$@" && pwd && echo && ls; }

    clip() { cat "$@" | xsel -b; }


    
    hit() { touch "$@" && chmod 755 "$@" && ls -la; }

    la() {
        if [ -z "$1" ]; then
            ls -ahlp
        else
            shopt -s dotglob nocaseglob; ls -adhlp [$1]* .[$1]*; shopt -u dotglob nocaseglob;
        fi
    }


# USER PATH
    
    if [ -f /etc/paths ]; then
        eval PATH=$(grep -v '^\s*$\|^\s*#' /etc/paths | paste -sd ":" -)
        export PATH
    fi


# USER VARIABLES

    PS1="\u@\h:\w \\$ "
    
    export EDITOR='nano'
    
    export VISUAL='nano'
    
    export HISTSIZE=500
    
    export HISTFILESIZE=500
    
    # for ookla-speedtest
    export NIXPKGS_ALLOW_UNFREE=1


echo "$HOME/.bashrc    ends."
