[ -z "$PS1" ] && return

echo "$HOME/.bashrc    starts."

# USER ALIAS

    alias down='docker compose down && docker ps -a && echo && docker volume ls && echo && docker network ls'

    alias downv='docker compose down -v && docker ps -a && echo && docker volume ls && echo && docker network ls'

    alias gpush="git add . && git commit -m 'cs' && git push"
    
    alias gpull="git stash && git fetch --all && git reset --hard origin master"
    
    alias hi=history

    alias ins='docker inspect'

    alias nls='docker network ls'
    
    alias pmg='python3 manage.py makemigrations && python3 manage.py migrate'
    
    alias prun='python3 manage.py runserver'
    
    alias pipup='pip3 install --upgrade pip'
    
    alias pipr='pip3 install -r requirements.txt'
    
    alias psa='docker ps -a'
    
    alias pvenv='python3 -m venv venv && source venv/bin/activate && pip3 install --upgrade pip && which python3 && python3 -V &&  pip3 -V &&  pip3 list'

    alias py=python3

    alias re="rsync -avP -e 'ssh -p 55555'"

    alias rm='rm -i'
    
    alias sha=sha256sum
    
    alias sou='source ~/.bashrc'
    
    alias sys='systemctl status --no-pager'
    
    alias sysen='sudo systemctl enable --now'
    
    alias sulo='sudo su --login'
    
    alias tip='cardano-cli query tip --mainnet'
    
    alias tnode='tmux attach -t node'
    
    alias tweb='tmux attach -t web'

    alias upd='docker compose up -d && docker ps -a && echo && docker network ls && echo && docker volume ls'
    
    alias venv='source venv/bin/activate'
    
    alias vls='docker volume ls'
    
    

# USER ENV

    PS1="\u@\h:\w \\$ "
    
    export EDITOR='nano'
    
    export VISUAL='nano'
    
    export HISTSIZE=500
    
    export HISTFILESIZE=500
    
    export NIXPKGS_ALLOW_UNFREE=1

    export PGDATA=/var/lib/pgsql/data


# USER FUNCTIONS

    cd() { builtin cd "$@" && ls -laph && echo && pwd && echo; }

    clip() { cat "$@" | xsel -b; }

    exec() { docker container exec -it "$@" /bin/bash; }
    
    hit() { touch "$@" && chmod 755 "$@" && ls -la; }

    la() {
        if [ -z "$1" ]; then
            ls -ahlp
        else
            shopt -s dotglob nocaseglob; ls -adhlp [$1]* .[$1]*; shopt -u dotglob nocaseglob;
        fi
    }


# USER PATH
    
    if [ -f /etc/paths ]; then
        eval PATH=$(grep -v '^\s*$\|^\s*#' /etc/paths | paste -sd ":" -)
        export PATH
    fi


echo "$HOME/.bashrc    ends."
