#!/usr/bin/env -S ansible-playbook

# remote_dir and local_dir need to have a trailing slash/# This goal of this playbook is to copy a folder from o2 to o1, 'fetch' module does not support copy a whole folder.

# RUN this playbook in local o1's tmux

# RUN this playbook in o1, o1 is the local machine

# o1 needs to define o2almalinux in o1's /etc/ansible/hosts

# o2 is the remote server


---
- name: Copy remote folder to localhost

  hosts: o2almalinux

  gather_facts: no

  vars:
    remote_dir: /tmp/dir2/
    local_dir: /tmp/dir1/

  tasks:
    - name: Ensure destination directory exists on localhost
      ansible.builtin.file:
        path: "{{ local_dir }}"
        state: directory
        mode: '0755'
      delegate_to: localhost


    - name: Copy directory from remote to localhost
      ansible.builtin.synchronize:
        src: "{{ remote_dir }}"
        dest: "{{ local_dir }}"
        mode: pull
        archive: yes
        recursive: yes


        
