#!/usr/bin/env -S ansible-playbook


---
- name: HARDEN ALMA
  hosts: localhost
  vars:
    ME: 'cs'

  pre_tasks:
    - name: Ensure the playbook is run as root
      fail:
        msg: "This playbook should be run as root."
      when: ansible_user_id != 'root'


  tasks:

    - name: Update all packages to the latest version
      ansible.builtin.dnf:
        name: "*"
        state: latest
        update_cache: yes


    - name: Install required security packages
      ansible.builtin.dnf:
        name:
          - fail2ban
          - firewalld
          - audit
        state: present


    - name: Enable and start firewalld
      ansible.builtin.service:
        name: firewalld
        state: started
        enabled: true


    - name: Disable unused firewall services
      ansible.builtin.firewalld:
        service: "{{ item }}"
        permanent: true
        state: disabled
      loop:
        - cockpit
        - dhcpv6-client   # dynamic IPv6
        - ssh


    - name: Configure firewall rules
      ansible.builtin.firewalld:
        service: "{{ item }}"
        permanent: true
        state: enabled
      loop:
        - http
        - https




    - name: reload_firewalld
      ansible.builtin.service:
        name: firewalld
        state: reloaded



    # after changing selinux config, reboot to take effect
    # make sure port 55555 enabled in SELINUX
    # I should enable SELINUX before SSHD port change
    - name: Enabled SELinux in config
      ansible.builtin.lineinfile:
        path: /etc/selinux/config
        regexp: '^SELINUX='
        line: 'SELINUX=enforcing'


    - name: Set SELinux type
      ansible.builtin.lineinfile:
        path: /etc/selinux/config
        regexp: '^SELINUXTYPE='
        line: 'SELINUXTYPE=targeted'


    - name: Ensure SELinux is enforcing
      ansible.builtin.command:
        cmd: "setenforce 1"
      register: selinux_status
      failed_when: selinux_status.rc != 0



    - name: Disable unused systemd services
      ansible.builtin.systemd:
        name: "{{ item }}"
        state: stopped
        enabled: false
      loop:
        - rpcbind  # samba and NFSv4 do not require rpcbind

    - name: Enable systemd services
      ansible.builtin.service:
        name: "{{ item }}"
        state: started
        enabled: true
      loop:
        - auditd
        - fail2ban
