#!/usr/bin/env -S ansible-playbook

---
- name: INSTALL NIX PACKAGES
  hosts: localhost
  become: no
  tasks:

    # fedora already has nc, ss, tmux
    - name: Install nix packages in fedora
      mynix:
        allow_unfree: yes
        update_cache: yes
        state: present
        repo: nixpkgs
        collect_garbage: yes
        list_packages: yes

        name:
          - bat
          - nmap
          - ookla-speedtest
          - tldr
      register: term

    - debug:
        var: term.stdout_lines
