#!/usr/bin/env -S ansible-playbook


---
- name: INSTALL APT PACKAGES
  hosts: localhost
  become: yes

  tasks:

    - name: Install packages
      ansible.builtin.package:
        name:
          - curl

          - firewalld

          - openssh-server

          - symlinks

          - xorgxrdp

          - xrdp

        state: present

    - name: Uninstall debain packages
      ansible.builtin.package:
        name:
          - ufw

        state: absent
