#!/usr/bin/env -S ansible-playbook

#1 Postgresql Server 16 requires this command to initialize DB before enabling systemd 
    # sudo postgresql-setup --initdb


---
- name: Install Ansible, PostgreSQL, MySQL, and Remove Unwanted Packages
  hosts: localhost
  become: yes
  tasks:
    - name: TASK 1 - INSTALL PACKAGES BY DNF
      ansible.builtin.dnf:
        name:
          - ansible
          - emacs-nox
        state: present
        update_cache: yes

    - name: Remove unwanted applications and clean up
      ansible.builtin.dnf:
        name:
          - "libreoffice*"
          - "java-21-openjdk-headless"
          - "geolite2-city"
          - "gnome-user-docs"
          - "nvidia-gpu-firmware"
          - "skopeo"
          - "thunderbird"
          - "rhythmbox"
          - "cheese"
          - "gnome-maps"
          - "gnome-photos"
          - "gnome-weather"
        state: absent
        autoremove: yes



