#!/usr/bin/env -S ansible-playbook

---
- name: INSTALL NIX PACKAGES

  hosts: localhost

  become: no

  pre_tasks:
    - name: Ensure the playbook is not run as root
      fail:
        msg: "This playbook cannot be run as root."
      when: ansible_user_id == 'root'

  tasks:

    # fedora already has nc, ss, tmux
    - name: Install nix packages in fedora
      mynix:
        allow_unfree: yes
        update_cache: yes
        state: present
        repo: nixpkgs
        collect_garbage: yes
        list_packages: yes

        name:
          - bat
          
          - nmap
          
          - ookla-speedtest  # binary is speedtest
          
          - tldr
      register: term

    - debug:
        var: term.stdout_lines
cs@o2:/data/o2/ansible $
