#!/usr/bin/env -S ansible-playbook

---
- name: Install Ansible, PostgreSQL, MySQL, and Remove Unwanted Packages
  hosts: localhost
  become: yes
  tasks:
    - name: Ensure Ansible, PostgreSQL, and MySQL are installed
      ansible.builtin.dnf:
        name:
          - ansible
          - mysql-server
        state: present
        update_cache: yes

    - name: Remove unwanted applications and clean up
      ansible.builtin.dnf:
        name:
          - "libreoffice*"
          - "java-21-openjdk-headless"          
          - "geolite2-city"
          - "gnome-user-docs"
          - "nvidia-gpu-firmware"
          - "skopeo"
          - "thunderbird"
          - "rhythmbox"
          - "cheese"
          - "gnome-maps"
          - "gnome-photos"
          - "gnome-weather"
        state: absent
        autoremove: yes

    - name: Enable and start MySQL
      ansible.builtin.systemd:
        name: mysqld
        enabled: yes
        state: started


