#!/usr/bin/env -S ansible-playbook

#1 Make sure sshd_config have the following lines for initial password login after fresh install:
  # PasswordAuthentication yes
  # UsePAM yes
  # Subsystem sftp /usr/libexec/openssh/sftp-server
  
#2 Set NOPASSWD in SUDOER file
  
  # sudo usermod -aG wheel cs   (optional: add user to wheel group)
  
  # sudo visudo   (use vi to edit sudoer file)
  # cs    ALL=(ALL)       NOPASSWD: ALL  (add this line at the bottom)
  
#3 Target machine has /home/cs/.ssh/authorized_keys key-based login
  
#4 do not use f-string to quote, this is not python code per se. 

---
- name: POST FEDORA
  hosts: fed
   

  tasks:

    - name: TASK 1 - Fetch user /etc/paths
      become: yes
      ansible.builtin.get_url:
        url: "https://chrissze.github.io/pub/linux/fedora_paths"
        dest: "/etc/paths"
        mode: '0644'
        owner: "{{ ansible_user_id }}"
        group: "{{ ansible_user_id }}"
        force: no
    
  
    - name: TASK 2 - Fetch ROOT /etc/rootpaths
      become: yes
      ansible.builtin.get_url:
        url: "https://chrissze.github.io/pub/linux/fedora_rootpaths"
        dest: "/etc/rootpaths"
        mode: '0644'
        owner: root
        force: no

  
    - name: TASK 3 - Fetch USER bashrc
      become: no
      ansible.builtin.get_url:
        url: "https://chrissze.github.io/pub/linux/user_bashrc"
        dest: "/home/{{ ansible_user_id }}/.bashrc"
        mode: '0644'
        owner: "{{ ansible_user_id }}"
        force: yes  # FORCED overwrite

    
    - name: TASK 4 - Fetch USER bash_profile
      become: no
      ansible.builtin.get_url:
        url: "https://chrissze.github.io/pub/linux/user_bash_profile"
        dest: "/home/{{ ansible_user_id }}/.bash_profile"
        mode: '0644'
        owner: "{{ ansible_user_id }}"
        force: yes  # FORCED overwrite

    
    - name: TASK 5 - Fetch ROOT bashrc
      become: yes
      ansible.builtin.get_url:
        url: "https://chrissze.github.io/pub/linux/root_bashrc"
        dest: "/root/.bashrc"
        mode: '0644'
        owner: root
        force: yes  # FORCED overwrite

    - name: TASK 6 - Fetch ROOT bash_profile
      become: yes
      ansible.builtin.get_url:
        url: "https://chrissze.github.io/pub/linux/bash_profile"
        dest: "/root/.bash_profile"
        mode: '0644'
        owner: root
        force: yes  # FORCED overwrite
