#!/usr/bin/env -S ansible-playbook

# ENSURE SELINUX IS ENABLED BEFORE CHANGING SSH PORT TO 5555
    # sestatus

#1 Run by root or add sudo when run this playbook
    
    # sudo ./setup.yaml

# In Alma 9, setroubleshoot package provides semanage


---
    - name: SSHD
      hosts: localhost
      become: yes
      
      tasks:

        - name: Install packages
          dnf:
            name:
              - firewalld
              - setroubleshoot
            state: present
    
        - name: Add port 55555 to SSH SELinux context 
          ansible.builtin.command:
            cmd: semanage port -a -t ssh_port_t -p tcp 55555

    
        - name: Open TCP ports in firewalld
          ansible.posix.firewalld:
            port: "{{ item }}/tcp"
            permanent: yes
            state: enabled
          loop:
            - 55555
    
    
        - name: Reload firewalld to apply changes
          ansible.builtin.service:
            name: firewalld
            state: reloaded


        - name: Backup /etc/ssh/sshd_config
          become: yes
          ansible.builtin.copy:
            src: "/etc/ssh/sshd_config"
            dest: "/etc/ssh/sshd_config.{{ ansible_date_time.time }}"
            #backup: no
    
        - name: Download file from web
          ansible.builtin.get_url:
            url: "https://chrissze.github.io/pub/linux/alma_sshd_config"
            dest: "/etc/ssh/sshd_config"
            mode: '0644'
            force: yes
    
    
        - name: Reload sshd to apply changes
          ansible.builtin.service:
            name: sshd
            state: reloaded
    
