#!/usr/bin/env -S ansible-playbook --ask-become-pass


# RESOLVE ROOT PASSWORD METHOD 1: ansible-playbook --ask-become-pass

# RESOLVE ROOT PASSWORD METHOD 2: chris ALL=(ALL) NOPASSWD: ALL    (visudo)

---
- name: SETUP MAC BASH
  hosts: localhost
  tasks:



    - name: TASK 1 - Ensure prompts.sh file exists
      become: no
      ansible.builtin.file:
        path: "/Users/{{ ansible_user_id }}/prompts.sh"
        state: touch
        owner: "{{ ansible_user_id }}"
        group: "staff"
        mode: '0644'



    - name: TASK 2 - Fetch USER bashrc
      become: no
      ansible.builtin.get_url:
        url: "https://chrissze.github.io/pub/mac/mac_user_bashrc"
        dest: "/Users/{{ ansible_user_id }}/.bashrc"
        mode: '0644'
        owner: "{{ ansible_user_id }}"
        group: "staff"
        force: yes         # FORCED overwrite



    - name: TASK 3 - Fetch USER bash_profile
      become: no
      ansible.builtin.get_url:
        url: "https://chrissze.github.io/pub/mac/mac_user_bash_profile"
        dest: "/Users/{{ ansible_user_id }}/.bash_profile"
        mode: '0644'
        owner: "{{ ansible_user_id }}"
        group: "staff"
        force: no




    - name: TASK 4 - Ensure ROOT prompts.sh file exists
      become: yes
      ansible.builtin.file:
        path: "/var/root/prompts.sh"
        state: touch
        owner: "root"
        group: "root"
        mode: '0644'


     
    - name: TASK 5 - Fetch ROOT bashrc
      become: yes
      ansible.builtin.get_url:
        url: "https://chrissze.github.io/pub/mac/mac_root_bashrc"
        dest: "/var/root/.bashrc"
        mode: '0644'
        owner: root
        force: yes # FORCED overwrite



    - name: TASK 6 - Fetch ROOT bash_profile
      become: yes
      ansible.builtin.get_url:
        url: "https://chrissze.github.io/pub/mac/mac_root_bash_profile"
        dest: "/var/root/.bash_profile"
        mode: '0644'
        owner: root
        force: no

