#!/usr/bin/env -S ansible-playbook --ask-become-pass




# REQUIRES REMOTE UBUNTU HAVE USER cs

# REQUIRES REMOTE UBUNTU HAVE PUBLIC KEY ~/.ssh/authorized_keys IN USER cs FOLDER

# REQUIRES LOCAL MAC HAVE PRIVATE KEY

# REQUIRES LOCAL MAC /etc/ansible/hosts HAVE A REMOTE UBUNTU SERVER ENTRY LIKE 
# o1ubuntu  ansible_host=o1.xyz  ansible_user=ubuntu  ansible_port=22


---
- name: Upload SSH key to remote user
  hosts: o1ubuntu
  become: true
  vars:
    USER1: cs
    MACUSER: chris
    local_key_path: "/Users/cs/.ssh/id_rsa"   # path on your Mac (controller)
    local_pub_path: "/Users/cs/.ssh/id_rsa.pub"
    

  tasks:
    - name: TASK - Ensure remote linux ~/.ssh exists with permission 0700
      ansible.builtin.file:
        path: "/home/{{ USER1 }}/.ssh"
        state: directory
        owner: "{{ USER1 }}"
        group: "{{ USER1 }}"
        mode: "0700"

    - name: TASK - Upload private key (id_rsa) with 0600 perms
      ansible.builtin.copy:
        src: "/Users/{{ MACUSER }}/.ssh/id_rsa"
        dest: "/home/{{ USER1 }}/.ssh/id_rsa"
        owner: "{{ USER1 }}"
        group: "{{ USER1 }}"
        mode: "0600"
      no_log: true          # don’t leak key contents in logs
