#!/usr/bin/env -S ansible-playbook

# REQUIRED ansible PROGRAM INSTALLED

# RUN BY ROOT - COPY AND PASTE INTO /var/tmp/setup_users.yaml, THEN chmod +x setup_users.yaml, FINALLY ./setup_users.yaml

# RERUN OK



# If the regexp line is omitted in lineinfile, there might be duplicate entries.

# create: false: Prevents accidental creation of the /etc/shadow file if it’s missing.

# If visudo validates the syntax as correct, Ansible applies the changes to /etc/sudoers. %s is the placeholder for the temporary file.

# In visudo command, the -c option tells visudo to check the syntax of a sudoers file. The -f option allows you to specify an alternate sudoers file to validate.

---
- name: SETUP UBUNTU USERS
  hosts: localhost
  become: yes
  vars:
      USER1: 'cs'

  tasks:
      - name: TASK 1 - Create docker group
        ansible.builtin.group:
            name: docker
            state: present


      - name: TASK 2 - Create user cs and add to docker, sudo group
        ansible.builtin.user:
            name: '{{ USER1 }}'
            groups:
              - '{{ USER1 }}'
              - docker
              - sudo
            append: yes
            state: present
            home: '/home/{{ USER1 }}'
            create_home: yes
            shell: /bin/bash     # ensures /bin/bash is the login shell


      - name: TASK 3 - Ensure user cs has sudo privilege without password
        ansible.builtin.lineinfile:
            path: /etc/sudoers
            regexp: '^cs ALL=.*'
            line: 'cs ALL=(ALL) NOPASSWD:ALL'
            validate: 'visudo -cf %s'
            state: present


      # cs password hint: HK lottery
      - name: TASK 4 - Set password hash for user cs in /etc/shadow
        ansible.builtin.lineinfile:
            path: /etc/shadow
            regexp: '^cs:'
            line: 'cs:$6$F4xFZOCHLFeHs5.5$2ruyjxl3qjDNSm93dpQHs325uqzb4v26bbggT.HYozE1HL6xh3Vfkdk2jjATo.vJhW/QNGOKnQjt.f7QXGbjQ/:19999:0:99999:7:::'
            create: false
            state: present


      # root password hint: St Paul grade 12 arts class
      - name: TASK 5 - Set password hash for root in /etc/shadow
        ansible.builtin.lineinfile:
            path: /etc/shadow
            regexp: '^root:'
            line: 'root:$6$rounds=100000$EznEqr238B4Z3Rtb$qwB/VyigFE1kO.EK15i7KXnCbE2NMVzS/XQPA/cakwr9VP6m/Qbc9mLt6ruDGIxNJYw.ezfx4BpgfTsTCRi.G0:20066:0:99999:7:::'
            create: false
            state: present




      - name: TASK 6 - Ensure ~/.ssh folder exists
        ansible.builtin.file:
            path: '/home/{{ USER1 }}/.ssh'
            state: directory
            mode: '0700'
            owner: '{{ USER1 }}'
            group: '{{ USER1 }}'



      - name: TASK 7 - Fetch user public key authorized_keys
        ansible.builtin.get_url:
            url: 'https://chrissze.github.io/pub/linux/authorized_keys'
            dest: '/home/{{ USER1 }}/.ssh/authorized_keys'
            mode: '0400'
            owner: '{{ USER1 }}'
            group: '{{ USER1 }}'
            force: no


      - name: TASK 8 - Fetch user public key authorized_keys2
        ansible.builtin.get_url:
            url: 'https://chrissze.github.io/pub/linux/authorized_keys2'
            dest: '/home/{{ USER1 }}/.ssh/authorized_keys2'
            mode: '0400'
            owner: '{{ USER1 }}'
            group: '{{ USER1 }}'
            force: no


      - name: TASK 9 - Fetch user ssh peer config
        ansible.builtin.get_url:
            url: 'https://chrissze.github.io/pub/linux/ssh_peer_config'
            dest: '/home/{{ USER1 }}/.ssh/config'
            mode: '0644'
            owner: '{{ USER1 }}'
            group: '{{ USER1 }}'
            force: no


      # VERIFY: git config --global user.name
      - name: TASK 10 - Set global Git user.name
        become_user: '{{ USER1 }}'
        command: git config --global user.name "o2cs"


      # VERIFY: git config --global user.email
      - name: TASK 11 - Set global Git user.email
        become_user: '{{ USER1 }}'
        command: git config --global user.email "chris_sze@yahoo.com"

