#!/usr/bin/env -S ansible-playbook --ask-become-pass




# REQUIRES REMOTE UBUNTU HAVE USER ubuntu

# REQUIRES REMOTE UBUNTU HAVE PUBLIC KEY ~/.ssh/authorized_keys IN USER ubuntu FOLDER

# REQUIRES LOCAL MAC HAVE PRIVATE KEY

# REQUIRES LOCAL MAC /etc/ansible/hosts HAVE A REMOTE UBUNTU SERVER ENTRY LIKE 
# o1ubuntu  ansible_host=o1.xyz  ansible_user=ubuntu  ansible_port=22


---
- name: SETUP UBUNTU SERVER BY LOCAL MAC
  hosts: o1ubuntu
  become: yes
  vars:
    USER1: cs
    MACUSER: chris
    

  tasks:
  
    - name: TASK 1 - Update, upgrade and clean apt
      become: yes
      ansible.builtin.apt:
        update_cache: true      # apt update
        upgrade: dist           # apt upgrade -y (dist-upgrade/full-upgrade)
        autoremove: true        # apt autoremove -y
        autoclean: true         # apt autoclean
        clean: true             # apt clean


    - name: TASK 2 - Install essential packages 
      become: yes
      ansible.builtin.apt:
        name: ansible
        state: present
    


    - name: TASK - Ensure remote linux /data exists
      become: yes
      ansible.builtin.file:
        path: "/data"
        state: directory
        owner: "{{ USER1 }}"
        group: "{{ USER1 }}"
        mode: "0755"

        
    - name: TASK - Ensure remote linux /github exists
      become: yes
      ansible.builtin.file:
        path: "/github"
        state: directory
        owner: "{{ USER1 }}"
        group: "{{ USER1 }}"
        mode: "0755"




    - name: TASK - Ensure remote linux /opt exists
      become: yes
      ansible.builtin.file:
        path: "/opt"
        state: directory
        owner: "root"
        group: "root"
        mode: "0755"


    - name: TASK - Ensure remote linux /opt/composes exists
      become: yes
      ansible.builtin.file:
        path: "/opt/composes"
        state: directory
        owner: "{{ USER1 }}"
        group: "{{ USER1 }}"
        mode: "0755"



    - name: TASK - Ensure remote linux ~/.ssh exists with permission 0700
      ansible.builtin.file:
        path: "/home/{{ USER1 }}/.ssh"
        state: directory
        owner: "{{ USER1 }}"
        group: "{{ USER1 }}"
        mode: "0700"



    - name: TASK - Upload private key (id_rsa) with 0600 perms
      ansible.builtin.copy:
        src: "/Users/{{ MACUSER }}/.ssh/id_rsa"
        dest: "/home/{{ USER1 }}/.ssh/id_rsa"
        owner: "{{ USER1 }}"
        group: "{{ USER1 }}"
        mode: "0600"
      no_log: true          # don’t leak key contents in logs
