#!/usr/bin/env -S ansible-playbook

# REQUIRED ansible PROGRAM INSTALLED

# RUN BY ROOT

# RERUN OK


---
- name: Install Docker on Ubuntu 24
  hosts: localhost
  become: true
  tasks:
  
    - name: Remove conflicting packages
      become: true
      apt:
        name:
          - docker.io
          - docker-doc
          - docker-compose
          - docker-compose-v2
          - podman-docker
        state: absent
      ignore_errors: true



    - name: Install prerequisites
      become: true
      apt:
        name:
          - ca-certificates
          - curl
          - firewalld
          - gnupg
        state: present
        update_cache: true







    - name: Add Docker GPG key
      shell: |
        install -m 0755 -d /etc/apt/keyrings
        curl -fsSL https://download.docker.com/linux/ubuntu/gpg | gpg --dearmor -o /etc/apt/keyrings/docker.gpg
        chmod a+r /etc/apt/keyrings/docker.gpg
      args:
        creates: /etc/apt/keyrings/docker.gpg

    - name: Add Docker apt repo (Noble)
      copy:
        dest: /etc/apt/sources.list.d/docker.list
        content: |
          deb [arch={{ ansible_architecture }} signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu noble stable

    - name: Update apt cache
      apt:
        update_cache: true

    - name: Install Docker Engine, CLI, containerd, Buildx, Compose v2
      apt:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
          - docker-buildx-plugin
          - docker-compose-plugin
        state: present

    - name: Ensure docker started and enabled
      systemd:
        name: docker
        enabled: true
        state: started

    - name: Add user cs to docker group
      user:
        name: cs
        groups: docker
        append: true
