#!/usr/bin/env -S ansible-playbook

# REQUIRED ansible PROGRAM INSTALLED

# RUN BY ROOT

# RERUN OK


---
- name: Install Docker on Ubuntu 24
  hosts: localhost
  become: true
  tasks:

    - name: TASK 1 - Collect service facts
      ansible.builtin.service_facts:

    - name: TASK 2 - Stop and disable UFW if installed
      ansible.builtin.systemd:
        name: ufw
        state: stopped
        enabled: false
        masked: false
      when: "'ufw.service' in ansible_facts.services"

  
    - name: Remove conflicting packages
      become: true
      apt:
        name:
          - docker.io
          - docker-doc
          - docker-compose
          - docker-compose-v2
          - podman-docker
          - ufw
        state: absent
      ignore_errors: true



    - name: Install prerequisites including firewalld
      become: true
      apt:
        name:
          - ca-certificates
          - curl
          - firewalld
          - gnupg
        state: present
        update_cache: true



    - name: Enable firewalld at boot and start it now
      become: true
      ansible.builtin.systemd:
        name: firewalld
        enabled: true
        state: started
        masked: false



    - name: Add HTTP/HTTPS services to the default zone (permanent)
      become: true
      ansible.posix.firewalld:
        service: "{{ item }}"
        permanent: yes
        state: enabled
      loop:
        - http
        - https







    - name: Add Docker GPG key
      become: true
      shell: |
        install -m 0755 -d /etc/apt/keyrings
        curl -fsSL https://download.docker.com/linux/ubuntu/gpg | gpg --dearmor -o /etc/apt/keyrings/docker.gpg
        chmod a+r /etc/apt/keyrings/docker.gpg
      args:
        creates: /etc/apt/keyrings/docker.gpg

    - name: Add Docker apt repo (Noble)
      become: true
      copy:
        dest: /etc/apt/sources.list.d/docker.list
        content: |
          deb [arch={{ ansible_architecture }} signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu noble stable


    - name: Update apt cache
      become: true
      apt:
        update_cache: true


    - name: Install Docker Engine for Ubuntu 24
      become: true
      apt:
        name:
          - containerd
          - docker.io
          - docker-buildx
          - docker-compose
          - docker-compose-v2
          - docker-clean
          - docker-doc
          - docker-registry
        state: present




    
    - name: Ensure docker started and enabled
      become: true
      ansible.builtin.systemd:
        name: docker
        enabled: true
        state: started
        masked: false



    - name: Add user cs to docker group
      become: true
      user:
        name: cs
        groups: docker
        append: true
